# Generated by Django 3.2.6 on 2021-10-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_lend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount_items',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
