# Generated by Django 3.2.6 on 2021-10-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_lend', '0002_alter_item_amount_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='borrower_fee',
            field=models.IntegerField(null=True),
        ),
    ]
