# Generated by Django 3.2.6 on 2021-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_lend', '0002_remove_history_borrower_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='late_day',
            field=models.IntegerField(null=True),
        ),
    ]
