# Generated by Django 3.2.9 on 2021-11-06 08:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ku_lend', '0003_history_late_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='late_day',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
